apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: rodobkn/expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name #We are indicating the value of the NATS_CLIENT_ID = pod name
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: REDIS_HOST
              value: expiration-redis-srv
