name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Grab all the code of the current repository
      - run: cd orders && npm install && npm run test:ci 
