name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**' # We will run the tests on a PR only if we make changes in the auth MS

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Grab all the code of the current repository
      - run: cd auth && npm install && npm run test:ci 
